### ISSUE TITLE
blackarchlinux-netinst-2014.10.07-i686.iso didn't boot

### ISSUE THREAD

**Issue by mbzadegan** [BlackArch/blackarch-iso#11]
Hi,
blackarchlinux-netinst-2014.10.07-i686.iso have not any boot switch and I changed its boot parameters to boot correctly.
Please resolve it on next release.
Thanks.

**Comment by noptrix** [comment]
known issue. will be fixed in the upcoming ISO releases

**Comment by 21stdragonhunter** [comment]
This is still an issue with blackarchlinux-live-2015..03.29-i686.iso

**Comment by mbzadegan** [comment]
yes, still do not resolve.
