### ISSUE TITLE
No option to boot latest BlackArch Live (ISO)

### ISSUE THREAD

**Issue by sutukh19** [BlackArch/blackarch-iso#12]
The latest LiveCD as of 08 April does not provide an option to boot the live CD.
BlackArch Linux 32 bit Live ISO 2015.04.08  c7ec7156e919a7ff8c5b7cb316c645fde5b580f0
The Options are as follows on the boot menu:
-Boot existing OS
-Run Memtest86+
-Hardware Information
-Reboot
-Power Off
If there is a workaround to get the disk booted any help will be greatly appreciated!

**Comment by noptrix** [comment]
r u trying to boot up the i686 iso on an x86_64 host system? this will fail. either use the x86_64 (recommended) or use i686 host system. btw, we are releasing the new ISOs in few days.
