### ISSUE TITLE
netinstall ISO Can't boot from PXE

### ISSUE THREAD

**Issue by yhfudev** [BlackArch/blackarch-iso#13]
The ISO file can't boot a i386 machine from PXE server,
it failed after select the default menu item and print out:

:: Mounting '/dev/disk/by-label/BLACKARCH_201507' to '/run/archiso/bootmnt'
Waiting 30 seconds for device /dev/disk/by-label/BLACKARCH_201507 ...
ERROR: '/dev/disk/by-label/BLACKARCH_201507' device did not show up after 30 seconds...
   Falling back to interactive prompt
   You can try to fix the problem manually, log out when you are finished

And the tftp config:
LABEL blackarchiso
    MENU LABEL blackarch iso
    KERNEL memdisk
    INITRD downloads/blackarchlinux-netinst-2015.07.31-i686.iso
    APPEND iso raw

**Comment by noptrix** [comment]
this should be fixed now with the new installers. can you please give a try?

**Comment by yhfudev** [comment]
I tested both in VM(pentium2) and an old laptop(Pentium M), it works now, thanks!
