### ISSUE TITLE
Live ISO boot error

### ISSUE THREAD

**Issue by yhfudev** [BlackArch/blackarch-iso#14]
Got a error message after booting to live from PXE server:

:: Mounting '192.168.1.1:/srv/tftp/images-live/blackarchlinux/2015.07.31/i686
:: Mounting /run/archiso/copytoram (tmpfs) filesystem, size=75%
:: Mounting /run/archiso/cowspace (tmpfs) filesystem, siz=256M...
:: Copying squashfs image to RAM...
cp: error writing '/run/archiso/copytoram/airootfs.sfs': No space left on device
ERROR: while copy '/run/archiso/bootmnt/arch/i686/airootfs.sfs' to '/run/archiso/copytoram/airootfs.sfs'

The RAM size of the machie is only 1G, and 770MB are mounted to /run/archiso/copytoram,
while the size of the file /run/archiso/bootmnt/arch/i686/airootfs.sfs is 4GB!

the tftp config:

LABEL blackarchlinux_2015.07.31_i686_live
    MENU LABEL blackarchlinux_2015.07.31_i686_live
    KERNEL images-live/blackarchlinux/2015.07.31/i686/arch/boot/i686/vmlinuz
    APPEND initrd=images-live/blackarchlinux/2015.07.31/i686/arch/boot/i686/archiso.img archisobasedir=arch archiso_nfs_srv=192.168.3.5:/srv/tftp/images-live/blackarchlinux/2015.07.31/i686 ip=:::::eth0:dhcp - arch=i686

**Comment by noptrix** [comment]
will be fixe din the upcoming ISOs (probably next week)
