### ISSUE TITLE
Won't boot in UEFI mode

### ISSUE THREAD

**Issue by RerumNovarum** [BlackArch/blackarch-iso#16]
Live ISO image from [http://blackarch.org/downloads.html](http://blackarch.org/downloads.html) (sha1sum: e113231bc0cd7d33219f9374f763ecd0887b6e5a)

Error message:
```
Error loading \EFI\blackarchiso\vmlinuz.efi: Not found
Failed to execute BlackArch Linux archiso x86_64 UEFI CD (\EFI\blackarchiso\vmlinuz.efi): Not found
```

EFI directory tree:
```
EFI
├── archiso
│   ├── archiso.img
│   ├── intel_ucode.img
│   └── vmlinuz.efi
├── boot
│   ├── bootx64.efi
│   ├── HashTool.efi
│   └── loader.efi
├── shellx64_v1.efi
└── shellx64_v2.efi

2 directories, 8 files
```

archiso-x86_64.conf:
```
linux   /EFI/blackarchiso/vmlinuz.efi
initrd  /EFI/blackarchiso/archiso.img
```
Paths in .conf need to be changed to /EFI/archiso/*

**Comment by noptrix** [comment]
thx, this will be fixed for the upcoming ISOs

**Comment by noptrix** [comment]
thx, fixed. the new ISOs will be released mid April.
