### ISSUE TITLE
UEFI

### ISSUE THREAD

**Issue by blazefade** [BlackArch/blackarch-iso#17]
Not sure what the issue is but it only seems to be with Arch-Anywhere and Blackarch but it stops loading and says it timed out causing complete failure on boot forcing the inability to install. Currently Running an I3 skylake intel processor on a UEFI system with windows 10. Blackarch has always been my distribution of choice and getting it installed again would be a blessing.

**Comment by heichblatt** [comment]
Duplicate of blackarch/blackarch#1154.
