### ISSUE TITLE
logind not working after install from iso

### ISSUE THREAD

**Issue by ikstream** [BlackArch/blackarch-iso#19]
The systemd-logind does not start after installing Blackarch from iso.
This happens on netinstall, as well as the live iso. 
If BlackArch is installed from repository this error is not encountered.
This occurs with encrypted, as well as unencrypted  root partition.
The machine hangs in this position and i have found no way so far to recover from it.

![snip_2017-04-29-22 34 08](https://cloud.githubusercontent.com/assets/5787845/25669064/cb0b2996-3028-11e7-8add-8d113ebe7e3b.jpg)

**Comment by noptrix** [comment]
just in case, can you reboot right after that and retry? and simply wait a bit / change to another console and change back, etc. see if you can get lxdm started

**Comment by ikstream** [comment]
Restart did not work, waiting did not help either. I will try the new image as soon a i can and report back.

**Comment by ikstream** [comment]
I can confirm, that this error does not occur with the netinstall iso. I encountered another error and will open an issue if i am sure this was not caused by my hasty install.
