### ISSUE TITLE
Blackarch boots only into CLI 

### ISSUE THREAD

**Issue by v00x** [BlackArch/blackarch-iso#20]
Sorry for this dumb question but when i start the live iso image it starts only in rootFS command mode. I haven't used the distro for a while so i downloaded the latest 32bit full version. 
```
startx
```
is not working so if there is another command tell me.. Or is bug or it's just me running into this issue.

**Comment by PedroSFreitas** [comment]
@v00x 
- UEFI or Legacy?
- How did you burn the ISO?

Is it similar to: https://github.com/BlackArch/blackarch/issues/1154 ?

**Comment by v00x** [comment]
i was usinf rufus, and i will try with a different software.
It was UEFI.

**Comment by PedroSFreitas** [comment]
@v00x please do. I'd just using `dd` if possible.
`dd bs=512M if=file.iso of=/dev/sdX` where X is the device you'll burn the ISO and file.iso is the iso you have downloaded.

If everything run smooth, consider closing this issue after.

Thanks.
Good luck.

**Comment by v00x** [comment]
I tried with Win32DiskImager and that solved my problem, the OS booted up properly. It's some kind of alternative to dd but for windows.
I coud done it on another linux but i didn't had time to do so and thanks i'm closing this issue!
