### ISSUE TITLE
WiFi not working with netinstall iso

### ISSUE THREAD

**Issue by k1ngf15h3r** [BlackArch/blackarch-iso#29]
Hi guys, I'd like to test blackarch on my notebook, but my "Intel Dual Wireless Card AC 3160" is not working with latest netinstall iso. Any hints to get this working?

Adding driver to netinstall usb drive should be an option, but I'm not that pro about this topic.

Any help is welcome :)

**Comment by ikstream** [comment]
Does your wifi device show up with ```iw dev```? Usually network is disable on blackarch isos
