### ISSUE TITLE
Boost.Python error in bootloader during Blackarch Linux dualboot with Windows 10

### ISSUE THREAD

**Issue by LukasAlstrup** [BlackArch/blackarch-iso#33]
I get Boost.Python error during installation of Blackarch Linux 64 bit Slim ISO version 2021.03.01 (4.5 GB) (GRAPHICAL INSTALLER). I have no clue what the error means and could not find someone with the same issue.

I selected a partition, where I wanted to install BlackArch, because I already have Windows 10 installed on my system on the same disk.

The installation is almost done when an error message pops up on my screen.

```
Installation failed
Boost.Python error in job "bootloader".
Command 'grub-install --target=x86-efi --efi-directory=/boot/efi --bootloader-id=BlackArch_Linux-force' returned non-zero exit status 1

Installing for x86_64 platform grub install error: cannot open '/boot/efi/EFI/BlackArch_Linux/grubx64efi': No such file or directory.
```

When I click on 'close', the installer stops, and I can restart the installation, just to get the same error.
It seems the installer is unable to install grub.

Screenshot of the error
![blackarcherror](https://user-images.githubusercontent.com/62612573/110842885-f6669780-82a7-11eb-81ee-5dbb182ee157.jpg)

The partition, where I want to install Blackarch.
![partitions](https://user-images.githubusercontent.com/62612573/110842863-ee0e5c80-82a7-11eb-87ed-aa0d6d1a8a14.PNG)

**Comment by Edu4rdSHL** [comment]
Hello, after testing myself I can't reproduce the issue. What I've followed in the disk partitioning step was:

Select "Replace a partition" and then click the partition where I want to install BlackArch.

![image](https://user-images.githubusercontent.com/32582878/110867652-19d41700-8295-11eb-8f74-c9eb321205da.png)

Everything finished sucessfully after doing it and BlackArch got installed alongside Windows

![image](https://user-images.githubusercontent.com/32582878/110867498-d7123f00-8294-11eb-841b-69dc4974050e.png)

**Comment by LukasAlstrup** [comment]
It sadly didn't work. I selected replace a partition, but it still gives the same error.
![blackarcherror2](https://user-images.githubusercontent.com/62612573/110907853-4d06bc80-830e-11eb-8091-9edbb3c1451e.jpg)

**Comment by aancw** [comment]
From the error message it said that one file is missing `/boot/etc/EFI/BlackArch_Linux/grubx64.efi

**Comment by aancw** [comment]
Wait, is /boot/efi user inputed?

**Comment by aancw** [comment]
For making it easier to trace the problem, can you repeat the installation process from the beginning and record your screen? Maybe it will be helpful.

**Comment by LukasAlstrup** [comment]
> Wait, is /boot/efi user inputed?
> 
> Ah i see it's from calamares https://github.com/BlackArch/blackarch-config-calamares/blob/f2021f57a95a782fa3a8794dc039f1c96ebd344d/calamares/modules/partition.conf#L9

Edu4rdSHL was so nice to help me on Discord. He told me, to edit my boot partition under the installation process and put in /boot/efi. I believe it was called flag.

**Comment by aancw** [comment]
> > Wait, is /boot/efi user inputed?
> > 
> > Ah i see it's from calamares https://github.com/BlackArch/blackarch-config-calamares/blob/f2021f57a95a782fa3a8794dc039f1c96ebd344d/calamares/modules/partition.conf#L9
> 
> Edu4rdSHL was so nice to help me on Discord. He told me, to edit my boot partition under the installation process and put in /boot/efi. I believe it was called flag.

Did this solve the problems?

**Comment by LukasAlstrup** [comment]
> > > Wait, is /boot/efi user inputed?
> > > Ah i see it's from calamares https://github.com/BlackArch/blackarch-config-calamares/blob/f2021f57a95a782fa3a8794dc039f1c96ebd344d/calamares/modules/partition.conf#L9
> > 
> > 
> > Edu4rdSHL was so nice to help me on Discord. He told me, to edit my boot partition under the installation process and put in /boot/efi. I believe it was called flag.
> 
> Did this solve the problems?

It gave the same error.
