### ISSUE TITLE
volatility-extra

### ISSUE THREAD

**Issue by yogistudio** [BlackArch/blackarch-iso#38]
volatility-extra cannot execute

**Comment by simonmysun** [comment]
```
/usr/bin/volatility-extra: line 3: /usr/bin/volatility: No such file or directory
```
I think it's looking for `/usr/bin/vol`.

**Comment by noraj** [comment]
```
$ pacman -Ql volatility3 | grep /bin
volatility3 /usr/bin/
volatility3 /usr/bin/vol
volatility3 /usr/bin/volshell
$ pacman -Ql volatility-extra | grep /bin
volatility-extra /usr/bin/
volatility-extra /usr/bin/volatility-extr
```

**Comment by simonmysun** [comment]
My result is rather different:

```
$ pacman -Qs volatility-extra
local/volatility-extra 92.d9fc072-2 (blackarch blackarch-forensic)
    Volatility plugins developed and maintained by the community.
$ pacman -Ql volatility-extra | grep /bin
volatility-extra /usr/bin/
volatility-extra /usr/bin/volatility-extra
$ cat /usr/bin/volatility-extra 
#!/bin/sh
cd /usr/share/volatility-extra
exec /usr/bin/volatility --plugins="/usr/share/volatility-extra" "$@"
```

and there is no `/usr/bin/volatility`

Am I out of sync?

**Comment by simonmysun** [comment]
Yes, I have it, but as you see:

```
$ pacman -Ql volatility3 | grep /bin
volatility3 /usr/bin/
volatility3 /usr/bin/vol
volatility3 /usr/bin/volshell
```

It doesn't have `/usr/bin/volatility`. If I let `volatility-extra` user `/usr/bin/vol` it shouts:

```
volatility: error: unrecognized arguments: --plugins=/usr/share/volatility-extra
```

**Comment by noraj** [comment]
`volatility-extra` works only for the old volatility 2

**Comment by simonmysun** [comment]
Shall we either remove it or add volatility 2 as its dependency? I feel it
doesn't make sense to install a package that won't work.

**Comment by noraj** [comment]
Volatility 2 isn't packaged anymore. We don't remove tool but we should definitly create an archive/old/deprecated category

**Comment by simonmysun** [comment]
I think you can add volatility 2 into deprecated category and correct the dependency of `volatility-extra` to it.

https://github.com/BlackArch/blackarch/blob/36466c9f039c22f16262e5b7b47745e650ac8d77/packages/volatility-extra/PKGBUILD#L12 Claiming it depends on `volatility3` is clearly a mistake.
