### ISSUE TITLE
Please add a manual installer for the Full Iso

### ISSUE THREAD

**Issue by BlackarchNet** [BlackArch/blackarch-iso#40]
I hate Blackarch-Installer and I hate Calamares, and would much rather Have a Pacstrap or Basestrap instead, you can call it Blackstrap or something, lmfao. If ArchLabs can have a Pacstrap of their own completely separate from the base Arch Pacstrap, If Artix can have basestrap why can't we have one of our very own?

**Comment by ikstream** [comment]
See BlackArch/blackarch#3399

**Comment by BlackarchNet** [comment]
> See [BlackArch/blackarch#3399](https://github.com/BlackArch/blackarch/issues/3399)
> 
> We don't have any intension to add such a tool, as pacstrap can easily be used with BlackArch

Care to elaborate? As I would assume using Pacstrap would just install base Arch Linux, not? And the main reason for me asking is I prefer my cipher, and for some reason I can't select GPT, as doing so results in the installer saying BTRFS & Fat 32 are invalid filesystems, so then I have to restart the script to get out of it, I'm speaking about the Full 15g iso for the record. Thanks for your help.
