### ISSUE TITLE
update your full iso

### ISSUE THREAD

**Issue by savolla** [BlackArch/blackarch-iso#41]
Full iso is from 2021 and it is nearly impossible to update without deleting bunch of dependencies and packages. Please update your full iso file and upload.

**Comment by noraj** [comment]
I think a new release is planned soon

**Comment by blackguy123456** [comment]
I just installed full iso the other day bare metal. I did have to remove about 20 or so tools until I could do the initial full system upgrade, but many of these tools I don’t need anyways. Kind of annoying but well worth it for me because this is my favorite OS to run ;)

**Comment by hamad12a** [comment]
I spend two days after this ISO! 
Cannot do anything, installing DM, upgrading,...

**Comment by anunna** [comment]
Released on 01.04.2023
