### ISSUE TITLE
iwd with resolvconf

### ISSUE THREAD

**Issue by notwidow** [BlackArch/blackarch-iso#44]
Hi, i removed networkmanager and other dhcp clients. anf only iwd is installed. Everything worked fine. iwd uses systemd and nameresolvingservice by default. but when i chnage this nameresolvingservice to resolvconf and tries to restart iwd then it does not start.... please. why iwd does not start when nameresolvingservice is set to resolvconf?

**Comment by noraj** [comment]
You must be talking about systemd-resolved and systemd-networkd. Have you tried https://wiki.archlinux.org/title/Iwd and https://wiki.archlinux.org/title/Openresolv
