### ISSUE TITLE
ı couldn't open blackarch on vmware

### ISSUE THREAD

**Issue by 03gayzer** [BlackArch/blackarch-iso#50]
![Ekran Görüntüsü (6)](https://github.com/BlackArch/blackarch/assets/107578096/196b7bda-2785-43fc-ada3-d71d27f45f26)
ı want to use blackarch on virtual machine but when ı import the iso file and start the system he gives me this error . what should ı do?

**Comment by 03gayzer** [comment]
can someone write something ?

**Comment by noraj** [comment]
Could you provide which ISO did you use? What are the characteristics of the VM (Legacy BIOS or UEFI) ?

**Comment by 03gayzer** [comment]
I tried all ISOs and they gave me the same error . ı didn't understand the second question ı just select creat virtual machine and ther is no bios or uefi options

**Comment by 03gayzer** [comment]
thank u all

**Comment by 03gayzer** [comment]
ı fixed guys the problem is low memory so you have to increase memory
