### ISSUE TITLE
dhcpcd is missing in full ISO

### ISSUE THREAD

**Issue by mgazzin** [BlackArch/blackarch-iso#54]
Hello, I am not getting IP address from router, but if I test with ethtool the link is up.
dhcpd service is missing.

**Comment by noraj** [comment]
Weird, seems there is dhclient and dhcpcd in all ISO:

https://github.com/search?q=repo%3ABlackArch%2Fblackarch-iso%20dhclient&type=code

**Comment by anunna** [comment]
Internet is disabled by default in the ISO for forensic reasons. As you and we have confirmed, dhcpcd is installed on the ISO but disabled.

**Comment by noraj** [comment]
Yay, no issue then.
